version: '3'
services:
  bookstore:
    image: bookstore:1.0.0
    #restart: always
    build: .
    network_mode: host
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver"
    container_name: bookstore
